input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "elastic"
    # We will read this from the Docker environment variable
    password => "${ELASTIC_PASSWORD}"
    # Critical for your self-signed certs:
    ssl_verification_mode => "none"
  }
}
